version: "3.5"
services:
  api:
    container_name: bragdocs
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    volumes:
      - ./:/app
