version: "3.5"
networks:
  bragdocs:
    driver: bridge
services:
  api:
    container_name: api
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    volumes:
      - ./:/app
    networks:
      - bragdocs
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.1
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      interval: 1s
      timeout: 5s
      retries: 3
    ports:
      - 5432:5432
    networks:
      - bragdocs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bragdocs"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  postgres_data:
